---
- hosts: all
  vars_files:
  - vars.yml
  become: true
  become_method: sudo

  pre_tasks:
    - name: Update apt-cache if needed.
      apt: update_cache=yes cache_valid_time=7200 

  handlers:
    - name: restart tomcat
      service: name=tomcat7 state=restarted

  tasks:
    - name: Install Tomcat 7.
      apt: "name={{ item }} state=installed"
      with_items:
        - tomcat7
        - tomcat7-admin

    - name: Ensure Tomcat 7 is started and enabled on boot
      service: name=tomcat7 state=started enabled=yes

    - name: Download Solr.
      get_url:
        url: "{{ solr_url }}"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        # sha256sum: "{{ solr_sha256_hash }}"

    - name: Expand Solr.
      command: >
        tar -C /tmp -xvzf {{ download_dir }}/solr-{{ solr_version }}.tgz
        creates={{ download_dir }}/solr-{{ solr_version }}/dist/solr-{{ solr_version }}.war

    - name: Ensure solr dir exists
      file: "name={{ solr_dir }} state=directory"

    - name: Copy Solr to the specified dir.
      command: >
        cp -r {{ download_dir }}/solr-{{ solr_version }}/. {{ solr_dir }}
        creates={{ solr_dir }}/dist/solr-{{ solr_version }}.war

    - name: Copy Solr components into place.
      shell: >
        cp -r {{ item.src }} {{ item.dest }}
        creates={{ item.creates }}
      with_items:
        - {
          src: "{{ solr_dir }}/example/webapps/solr.war",
          dest: "{{ solr_dir }}/solr.war",
          creates: "{{ solr_dir }}/solr.war"
        }
        - {
          src: "{{ solr_dir }}/example/solr/*",
          dest: "{{ solr_dir }}/",
          creates: "{{ solr_dir }}/solr.xml"
        }
        # log4j config
        - {
          src: "{{ solr_dir }}/example/lib/ext/*",
          dest: "/var/lib/tomcat7/shared/",
          creates: "/var/lib/tomcat7/shared/log4j-1.2.17.jar"
        }
        - {
          src: "{{ solr_dir }}/example/resources/log4j.properties",
          dest: "/var/lib/tomcat7/shared/classes",
          creates: "/var/lib/tomcat7/shared/classes/log4j.properties"
        }
      notify: restart tomcat

    - name: Ensure solr example dir is absent.
      file: 
        path: "{{ solr_dir }}/example"
        state: absent

    - name: Set up solr data dir.
      file:
        path: "{{ solr_dir }}/data"
        state: directory
        owner: tomcat7
        group: tomcat7

    - name: Configure solrconfig.xml for new data directory.
      lineinfile:
        dest: "{{ solr_dir }}/collection1/conf/solrconfig.xml"
        regexp: "^.*<dataDir.+$"
        line: "<dataDir>${solr.data.dir:{{ solr_dir }}/data}</dataDir>"
        state: present

    - name: Set permissions for solr home.
      file:
        path: "{{ solr_dir }}"
        recurse: yes
        owner: tomcat7
        group: tomcat7

    - name: Add Catalina configuration for solr.
      template:
          src: templates/solr.xml.j2
          dest: /etc/tomcat7/Catalina/localhost/solr.xml
          owner: root
          group: tomcat7
          mode: 0644
      notify: restart tomcat