# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.vm.define "lampdrupal" do |app|
    app.vm.hostname = "lamp.dev"
    app.vm.box = "ubuntu/trusty64"
    app.vm.network :private_network, ip: "192.168.60.2"
  end
end
